export enum PACKAGE_TYPE {
  AI_CONVERSATION = "AI_CONVERSATION",
  ROADMAP_UNLOCK = "ROADMAP_UNLOCK",
  VIDEO_LESSON = "VIDEO_LESSON",
  GRAMMAR_CHECKER = "GRAMMAR_CHECKER",
}

export default PACKAGE_TYPE;
